language: cpp

compiler:  
    - gcc
    - clang

before_script:  
    - sudo apt-get update -qq
    - sudo apt-get install -y maven
    - mkdir build
    - cd build
    - cmake -DBUILD_WITH_TESTS=ON -DGPC_ROOT_DIR="/home/travis/build/CallForSanity/Gaalop/build"  -DGPC_INCLUDE_DIR="/home/travis/build/CallForSanity/Gaalop/build/include" -DGPC_JAR="/home/travis/build/CallForSanity/Gaalop/build/share/gpc/gaalop/starter-1.0.0.jar" ..

script: make

after_script:
    - make test
