language: cpp

compiler:  
    - gcc
    - clang

before_script:  
    - sudo apt-get update -qq
    - sudo apt-get install -y maven
    - mkdir build
    - cd build
    - cmake -DBUILD_WITH_TESTS=ON ..

script: make

after_script:
    - make test
